[UI]
# Nom que apareixerà a la part superior de la pàgina
name = "Assistent AIPDE - RAG - IT Green"

# Descripció per defecte per a xarxes socials
description = "Un assistent de xat amb RAG creat amb Chainlit."

# Url al teu logo. Ha de començar amb /public/
logo = "/public/logo.png"

# Url al logo en mode fosc (opcional, si és diferent)
# logo_dark = "/public/logo_dark.png"

# Url al favicon
favicon = "/public/logo.png"

[UI.theme]
# Pots personalitzar els colors si vols
# primary_color = "#F80000"