name: deploy-mcp-chat

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'k3s/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      REGISTRY_HOST: ${{ vars.REGISTRY_HOST }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_HOST }}/mcp/mcp-chat:latest
            ${{ env.REGISTRY_HOST }}/mcp/mcp-chat:${{ github.sha }}

      - name: Kubeconfig
        run: |
          echo "Exportant KUBECONFIG per apuntar a k3s"
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl version --short || true

      - name: Create or update regcred secret
        run: |
          kubectl get ns mcp-llm >/dev/null 2>&1 || kubectl create ns mcp-llm
          kubectl -n mcp-llm delete secret regcred >/dev/null 2>&1 || true
          kubectl -n mcp-llm create secret docker-registry regcred \
            --docker-server=${{ env.REGISTRY_HOST }} \
            --docker-username=${{ secrets.REGISTRY_USERNAME }} \
            --docker-password=${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy manifests
        run: |
          kubectl apply -f k3s/llama-cpp.yaml
          kubectl apply -f k3s/mcp-chat.yaml

      - name: Rollout status
        run: |
          kubectl -n mcp-llm rollout status deploy/mcp-chat --timeout=120s

