name: Build and Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted # Es correrà en el teu runner self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }} # Ex: registry.teva-empresa.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Get current date as tag
        id: date
        run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          make push TAG=${{ env.TAG }}
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}

  deploy-to-k3s:
    runs-on: self-hosted
    needs: build-and-push # Aquest job depèn de l'anterior
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
      - name: Get latest tag
        id: date
        run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
      - name: Deploy to K3s cluster
        run: |
          make deploy TAG=${{ env.TAG }}
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}